name: DocFX

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: DocFX
        shell: cmd
        run: |
          choco install docfx -y
          docfx docfx\docfx.json

      - name: Upload DocFX packages
        uses: actions/upload-artifact@v2
        with:
          name: docfx_site
          path: ${{ github.workspace }}\docfx\_site

      - name: Publish Documentation on GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docfx/_site
