// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLModel_ConsoleApp2
{
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"col0")]
            public float Col0 { get; set; }

            [ColumnName(@"col1")]
            public float Col1 { get; set; }

            [ColumnName(@"col2")]
            public float Col2 { get; set; }

            [ColumnName(@"col3")]
            public float Col3 { get; set; }

            [ColumnName(@"col4")]
            public float Col4 { get; set; }

            [ColumnName(@"col5")]
            public float Col5 { get; set; }

            [ColumnName(@"col6")]
            public float Col6 { get; set; }

            [ColumnName(@"col7")]
            public float Col7 { get; set; }

            [ColumnName(@"col8")]
            public float Col8 { get; set; }

            [ColumnName(@"col9")]
            public float Col9 { get; set; }

            [ColumnName(@"col10")]
            public float Col10 { get; set; }

            [ColumnName(@"col11")]
            public float Col11 { get; set; }

            [ColumnName(@"col12")]
            public float Col12 { get; set; }

            [ColumnName(@"col13")]
            public float Col13 { get; set; }

            [ColumnName(@"col14")]
            public float Col14 { get; set; }

            [ColumnName(@"col15")]
            public float Col15 { get; set; }

            [ColumnName(@"col16")]
            public float Col16 { get; set; }

            [ColumnName(@"col17")]
            public float Col17 { get; set; }

            [ColumnName(@"col18")]
            public float Col18 { get; set; }

            [ColumnName(@"col19")]
            public float Col19 { get; set; }

            [ColumnName(@"col20")]
            public float Col20 { get; set; }

            [ColumnName(@"col21")]
            public float Col21 { get; set; }

            [ColumnName(@"col22")]
            public float Col22 { get; set; }

            [ColumnName(@"col23")]
            public float Col23 { get; set; }

            [ColumnName(@"col24")]
            public float Col24 { get; set; }

            [ColumnName(@"col25")]
            public float Col25 { get; set; }

            [ColumnName(@"col26")]
            public float Col26 { get; set; }

            [ColumnName(@"col27")]
            public float Col27 { get; set; }

            [ColumnName(@"col28")]
            public float Col28 { get; set; }

            [ColumnName(@"col29")]
            public float Col29 { get; set; }

            [ColumnName(@"col30")]
            public float Col30 { get; set; }

            [ColumnName(@"col31")]
            public float Col31 { get; set; }

            [ColumnName(@"col32")]
            public float Col32 { get; set; }

            [ColumnName(@"col33")]
            public float Col33 { get; set; }

            [ColumnName(@"col34")]
            public float Col34 { get; set; }

            [ColumnName(@"col35")]
            public float Col35 { get; set; }

            [ColumnName(@"col36")]
            public float Col36 { get; set; }

            [ColumnName(@"col37")]
            public float Col37 { get; set; }

            [ColumnName(@"col38")]
            public float Col38 { get; set; }

            [ColumnName(@"col39")]
            public float Col39 { get; set; }

            [ColumnName(@"col40")]
            public float Col40 { get; set; }

            [ColumnName(@"col41")]
            public float Col41 { get; set; }

            [ColumnName(@"col42")]
            public float Col42 { get; set; }

            [ColumnName(@"col43")]
            public float Col43 { get; set; }

            [ColumnName(@"col44")]
            public float Col44 { get; set; }

            [ColumnName(@"col45")]
            public float Col45 { get; set; }

            [ColumnName(@"col46")]
            public float Col46 { get; set; }

            [ColumnName(@"col47")]
            public float Col47 { get; set; }

            [ColumnName(@"col48")]
            public float Col48 { get; set; }

            [ColumnName(@"col49")]
            public float Col49 { get; set; }

            [ColumnName(@"col50")]
            public float Col50 { get; set; }

            [ColumnName(@"col51")]
            public float Col51 { get; set; }

            [ColumnName(@"col52")]
            public float Col52 { get; set; }

            [ColumnName(@"col53")]
            public float Col53 { get; set; }

            [ColumnName(@"col54")]
            public float Col54 { get; set; }

            [ColumnName(@"col55")]
            public float Col55 { get; set; }

            [ColumnName(@"col56")]
            public float Col56 { get; set; }

            [ColumnName(@"col57")]
            public float Col57 { get; set; }

            [ColumnName(@"col58")]
            public float Col58 { get; set; }

            [ColumnName(@"col59")]
            public float Col59 { get; set; }

            [ColumnName(@"col60")]
            public float Col60 { get; set; }

            [ColumnName(@"col61")]
            public float Col61 { get; set; }

            [ColumnName(@"col62")]
            public float Col62 { get; set; }

            [ColumnName(@"col63")]
            public float Col63 { get; set; }

            [ColumnName(@"col64")]
            public float Col64 { get; set; }

            [ColumnName(@"col65")]
            public float Col65 { get; set; }

            [ColumnName(@"col66")]
            public float Col66 { get; set; }

            [ColumnName(@"col67")]
            public float Col67 { get; set; }

            [ColumnName(@"col68")]
            public float Col68 { get; set; }

            [ColumnName(@"col69")]
            public float Col69 { get; set; }

            [ColumnName(@"col70")]
            public float Col70 { get; set; }

            [ColumnName(@"col71")]
            public float Col71 { get; set; }

            [ColumnName(@"col72")]
            public float Col72 { get; set; }

            [ColumnName(@"col73")]
            public float Col73 { get; set; }

            [ColumnName(@"col74")]
            public float Col74 { get; set; }

            [ColumnName(@"col75")]
            public float Col75 { get; set; }

            [ColumnName(@"col76")]
            public float Col76 { get; set; }

            [ColumnName(@"col77")]
            public float Col77 { get; set; }

            [ColumnName(@"col78")]
            public float Col78 { get; set; }

            [ColumnName(@"col79")]
            public float Col79 { get; set; }

            [ColumnName(@"col80")]
            public float Col80 { get; set; }

            [ColumnName(@"col81")]
            public float Col81 { get; set; }

            [ColumnName(@"col82")]
            public float Col82 { get; set; }

            [ColumnName(@"col83")]
            public float Col83 { get; set; }

            [ColumnName(@"col84")]
            public float Col84 { get; set; }

            [ColumnName(@"col85")]
            public float Col85 { get; set; }

            [ColumnName(@"col86")]
            public float Col86 { get; set; }

            [ColumnName(@"col87")]
            public float Col87 { get; set; }

            [ColumnName(@"col88")]
            public float Col88 { get; set; }

            [ColumnName(@"col89")]
            public float Col89 { get; set; }

            [ColumnName(@"col90")]
            public float Col90 { get; set; }

            [ColumnName(@"col91")]
            public float Col91 { get; set; }

            [ColumnName(@"col92")]
            public float Col92 { get; set; }

            [ColumnName(@"col93")]
            public float Col93 { get; set; }

            [ColumnName(@"col94")]
            public float Col94 { get; set; }

            [ColumnName(@"col95")]
            public float Col95 { get; set; }

            [ColumnName(@"col96")]
            public float Col96 { get; set; }

            [ColumnName(@"col97")]
            public float Col97 { get; set; }

            [ColumnName(@"col98")]
            public float Col98 { get; set; }

            [ColumnName(@"col99")]
            public float Col99 { get; set; }

            [ColumnName(@"col100")]
            public float Col100 { get; set; }

            [ColumnName(@"col101")]
            public float Col101 { get; set; }

            [ColumnName(@"col102")]
            public float Col102 { get; set; }

            [ColumnName(@"col103")]
            public float Col103 { get; set; }

            [ColumnName(@"col104")]
            public float Col104 { get; set; }

            [ColumnName(@"col105")]
            public float Col105 { get; set; }

            [ColumnName(@"col106")]
            public float Col106 { get; set; }

            [ColumnName(@"col107")]
            public float Col107 { get; set; }

            [ColumnName(@"col108")]
            public float Col108 { get; set; }

            [ColumnName(@"col109")]
            public float Col109 { get; set; }

            [ColumnName(@"col110")]
            public float Col110 { get; set; }

            [ColumnName(@"col111")]
            public float Col111 { get; set; }

            [ColumnName(@"col112")]
            public float Col112 { get; set; }

            [ColumnName(@"col113")]
            public float Col113 { get; set; }

            [ColumnName(@"col114")]
            public float Col114 { get; set; }

            [ColumnName(@"col115")]
            public float Col115 { get; set; }

            [ColumnName(@"col116")]
            public float Col116 { get; set; }

            [ColumnName(@"col117")]
            public float Col117 { get; set; }

            [ColumnName(@"col118")]
            public float Col118 { get; set; }

            [ColumnName(@"col119")]
            public float Col119 { get; set; }

            [ColumnName(@"col120")]
            public float Col120 { get; set; }

            [ColumnName(@"col121")]
            public float Col121 { get; set; }

            [ColumnName(@"col122")]
            public float Col122 { get; set; }

            [ColumnName(@"col123")]
            public float Col123 { get; set; }

            [ColumnName(@"col124")]
            public float Col124 { get; set; }

            [ColumnName(@"col125")]
            public float Col125 { get; set; }

            [ColumnName(@"col126")]
            public float Col126 { get; set; }

            [ColumnName(@"col127")]
            public float Col127 { get; set; }

            [ColumnName(@"col128")]
            public float Col128 { get; set; }

            [ColumnName(@"col129")]
            public float Col129 { get; set; }

            [ColumnName(@"col130")]
            public float Col130 { get; set; }

            [ColumnName(@"col131")]
            public float Col131 { get; set; }

            [ColumnName(@"col132")]
            public float Col132 { get; set; }

            [ColumnName(@"col133")]
            public float Col133 { get; set; }

            [ColumnName(@"col134")]
            public float Col134 { get; set; }

            [ColumnName(@"col135")]
            public float Col135 { get; set; }

            [ColumnName(@"col136")]
            public float Col136 { get; set; }

            [ColumnName(@"col137")]
            public float Col137 { get; set; }

            [ColumnName(@"col138")]
            public float Col138 { get; set; }

            [ColumnName(@"col139")]
            public float Col139 { get; set; }

            [ColumnName(@"col140")]
            public float Col140 { get; set; }

            [ColumnName(@"col141")]
            public float Col141 { get; set; }

            [ColumnName(@"col142")]
            public float Col142 { get; set; }

            [ColumnName(@"col143")]
            public float Col143 { get; set; }

            [ColumnName(@"col144")]
            public float Col144 { get; set; }

            [ColumnName(@"col145")]
            public float Col145 { get; set; }

            [ColumnName(@"col146")]
            public float Col146 { get; set; }

            [ColumnName(@"col147")]
            public float Col147 { get; set; }

            [ColumnName(@"col148")]
            public float Col148 { get; set; }

            [ColumnName(@"col149")]
            public float Col149 { get; set; }

            [ColumnName(@"col150")]
            public float Col150 { get; set; }

            [ColumnName(@"col151")]
            public float Col151 { get; set; }

            [ColumnName(@"col152")]
            public float Col152 { get; set; }

            [ColumnName(@"col153")]
            public float Col153 { get; set; }

            [ColumnName(@"col154")]
            public float Col154 { get; set; }

            [ColumnName(@"col155")]
            public float Col155 { get; set; }

            [ColumnName(@"col156")]
            public float Col156 { get; set; }

            [ColumnName(@"col157")]
            public float Col157 { get; set; }

            [ColumnName(@"col158")]
            public float Col158 { get; set; }

            [ColumnName(@"col159")]
            public float Col159 { get; set; }

            [ColumnName(@"col160")]
            public float Col160 { get; set; }

            [ColumnName(@"col161")]
            public float Col161 { get; set; }

            [ColumnName(@"col162")]
            public float Col162 { get; set; }

            [ColumnName(@"col163")]
            public float Col163 { get; set; }

            [ColumnName(@"col164")]
            public float Col164 { get; set; }

            [ColumnName(@"col165")]
            public float Col165 { get; set; }

            [ColumnName(@"col166")]
            public float Col166 { get; set; }

            [ColumnName(@"col167")]
            public float Col167 { get; set; }

            [ColumnName(@"col168")]
            public float Col168 { get; set; }

            [ColumnName(@"col169")]
            public float Col169 { get; set; }

            [ColumnName(@"col170")]
            public float Col170 { get; set; }

            [ColumnName(@"col171")]
            public float Col171 { get; set; }

            [ColumnName(@"col172")]
            public float Col172 { get; set; }

            [ColumnName(@"col173")]
            public float Col173 { get; set; }

            [ColumnName(@"col174")]
            public float Col174 { get; set; }

            [ColumnName(@"col175")]
            public float Col175 { get; set; }

            [ColumnName(@"col176")]
            public float Col176 { get; set; }

            [ColumnName(@"col177")]
            public float Col177 { get; set; }

            [ColumnName(@"col178")]
            public float Col178 { get; set; }

            [ColumnName(@"col179")]
            public float Col179 { get; set; }

            [ColumnName(@"col180")]
            public float Col180 { get; set; }

            [ColumnName(@"col181")]
            public float Col181 { get; set; }

            [ColumnName(@"col182")]
            public float Col182 { get; set; }

            [ColumnName(@"col183")]
            public float Col183 { get; set; }

            [ColumnName(@"col184")]
            public float Col184 { get; set; }

            [ColumnName(@"col185")]
            public float Col185 { get; set; }

            [ColumnName(@"col186")]
            public float Col186 { get; set; }

            [ColumnName(@"col187")]
            public float Col187 { get; set; }

            [ColumnName(@"col188")]
            public float Col188 { get; set; }

            [ColumnName(@"col189")]
            public float Col189 { get; set; }

            [ColumnName(@"col190")]
            public float Col190 { get; set; }

            [ColumnName(@"col191")]
            public float Col191 { get; set; }

            [ColumnName(@"col192")]
            public float Col192 { get; set; }

            [ColumnName(@"col193")]
            public float Col193 { get; set; }

            [ColumnName(@"col194")]
            public float Col194 { get; set; }

            [ColumnName(@"col195")]
            public float Col195 { get; set; }

            [ColumnName(@"col196")]
            public float Col196 { get; set; }

            [ColumnName(@"col197")]
            public float Col197 { get; set; }

            [ColumnName(@"col198")]
            public float Col198 { get; set; }

            [ColumnName(@"col199")]
            public float Col199 { get; set; }

            [ColumnName(@"col200")]
            public float Col200 { get; set; }

            [ColumnName(@"col201")]
            public float Col201 { get; set; }

            [ColumnName(@"col202")]
            public float Col202 { get; set; }

            [ColumnName(@"col203")]
            public float Col203 { get; set; }

            [ColumnName(@"col204")]
            public float Col204 { get; set; }

            [ColumnName(@"col205")]
            public float Col205 { get; set; }

            [ColumnName(@"col206")]
            public float Col206 { get; set; }

            [ColumnName(@"col207")]
            public float Col207 { get; set; }

            [ColumnName(@"col208")]
            public float Col208 { get; set; }

            [ColumnName(@"col209")]
            public float Col209 { get; set; }

            [ColumnName(@"col210")]
            public float Col210 { get; set; }

            [ColumnName(@"col211")]
            public float Col211 { get; set; }

            [ColumnName(@"col212")]
            public float Col212 { get; set; }

            [ColumnName(@"col213")]
            public float Col213 { get; set; }

            [ColumnName(@"col214")]
            public float Col214 { get; set; }

            [ColumnName(@"col215")]
            public float Col215 { get; set; }

            [ColumnName(@"col216")]
            public float Col216 { get; set; }

            [ColumnName(@"col217")]
            public float Col217 { get; set; }

            [ColumnName(@"col218")]
            public float Col218 { get; set; }

            [ColumnName(@"col219")]
            public float Col219 { get; set; }

            [ColumnName(@"col220")]
            public float Col220 { get; set; }

            [ColumnName(@"col221")]
            public float Col221 { get; set; }

            [ColumnName(@"col222")]
            public float Col222 { get; set; }

            [ColumnName(@"col223")]
            public float Col223 { get; set; }

            [ColumnName(@"col224")]
            public float Col224 { get; set; }

            [ColumnName(@"col225")]
            public float Col225 { get; set; }

            [ColumnName(@"col226")]
            public float Col226 { get; set; }

            [ColumnName(@"col227")]
            public float Col227 { get; set; }

            [ColumnName(@"col228")]
            public float Col228 { get; set; }

            [ColumnName(@"col229")]
            public float Col229 { get; set; }

            [ColumnName(@"col230")]
            public float Col230 { get; set; }

            [ColumnName(@"col231")]
            public float Col231 { get; set; }

            [ColumnName(@"col232")]
            public float Col232 { get; set; }

            [ColumnName(@"col233")]
            public float Col233 { get; set; }

            [ColumnName(@"col234")]
            public float Col234 { get; set; }

            [ColumnName(@"col235")]
            public float Col235 { get; set; }

            [ColumnName(@"col236")]
            public float Col236 { get; set; }

            [ColumnName(@"col237")]
            public float Col237 { get; set; }

            [ColumnName(@"col238")]
            public float Col238 { get; set; }

            [ColumnName(@"col239")]
            public float Col239 { get; set; }

            [ColumnName(@"col240")]
            public float Col240 { get; set; }

            [ColumnName(@"col241")]
            public float Col241 { get; set; }

            [ColumnName(@"col242")]
            public float Col242 { get; set; }

            [ColumnName(@"col243")]
            public float Col243 { get; set; }

            [ColumnName(@"col244")]
            public float Col244 { get; set; }

            [ColumnName(@"col245")]
            public float Col245 { get; set; }

            [ColumnName(@"col246")]
            public float Col246 { get; set; }

            [ColumnName(@"col247")]
            public float Col247 { get; set; }

            [ColumnName(@"col248")]
            public float Col248 { get; set; }

            [ColumnName(@"col249")]
            public float Col249 { get; set; }

            [ColumnName(@"col250")]
            public float Col250 { get; set; }

            [ColumnName(@"col251")]
            public float Col251 { get; set; }

            [ColumnName(@"col252")]
            public float Col252 { get; set; }

            [ColumnName(@"col253")]
            public float Col253 { get; set; }

            [ColumnName(@"col254")]
            public float Col254 { get; set; }

            [ColumnName(@"col255")]
            public float Col255 { get; set; }

            [ColumnName(@"col256")]
            public float Col256 { get; set; }

            [ColumnName(@"col257")]
            public float Col257 { get; set; }

            [ColumnName(@"col258")]
            public float Col258 { get; set; }

            [ColumnName(@"col259")]
            public float Col259 { get; set; }

            [ColumnName(@"col260")]
            public float Col260 { get; set; }

            [ColumnName(@"col261")]
            public float Col261 { get; set; }

            [ColumnName(@"col262")]
            public float Col262 { get; set; }

            [ColumnName(@"col263")]
            public float Col263 { get; set; }

            [ColumnName(@"col264")]
            public float Col264 { get; set; }

            [ColumnName(@"col265")]
            public float Col265 { get; set; }

            [ColumnName(@"col266")]
            public float Col266 { get; set; }

            [ColumnName(@"col267")]
            public float Col267 { get; set; }

            [ColumnName(@"col268")]
            public float Col268 { get; set; }

            [ColumnName(@"col269")]
            public float Col269 { get; set; }

            [ColumnName(@"col270")]
            public float Col270 { get; set; }

            [ColumnName(@"col271")]
            public float Col271 { get; set; }

            [ColumnName(@"col272")]
            public float Col272 { get; set; }

            [ColumnName(@"col273")]
            public float Col273 { get; set; }

            [ColumnName(@"col274")]
            public float Col274 { get; set; }

            [ColumnName(@"col275")]
            public float Col275 { get; set; }

            [ColumnName(@"col276")]
            public float Col276 { get; set; }

            [ColumnName(@"col277")]
            public float Col277 { get; set; }

            [ColumnName(@"col278")]
            public float Col278 { get; set; }

            [ColumnName(@"col279")]
            public float Col279 { get; set; }

            [ColumnName(@"col280")]
            public float Col280 { get; set; }

            [ColumnName(@"col281")]
            public float Col281 { get; set; }

            [ColumnName(@"col282")]
            public float Col282 { get; set; }

            [ColumnName(@"col283")]
            public float Col283 { get; set; }

            [ColumnName(@"col284")]
            public float Col284 { get; set; }

            [ColumnName(@"col285")]
            public float Col285 { get; set; }

            [ColumnName(@"col286")]
            public float Col286 { get; set; }

            [ColumnName(@"col287")]
            public float Col287 { get; set; }

            [ColumnName(@"col288")]
            public float Col288 { get; set; }

            [ColumnName(@"col289")]
            public float Col289 { get; set; }

            [ColumnName(@"col290")]
            public float Col290 { get; set; }

            [ColumnName(@"col291")]
            public float Col291 { get; set; }

            [ColumnName(@"col292")]
            public float Col292 { get; set; }

            [ColumnName(@"col293")]
            public float Col293 { get; set; }

            [ColumnName(@"col294")]
            public float Col294 { get; set; }

            [ColumnName(@"col295")]
            public float Col295 { get; set; }

            [ColumnName(@"col296")]
            public float Col296 { get; set; }

            [ColumnName(@"col297")]
            public float Col297 { get; set; }

            [ColumnName(@"col298")]
            public float Col298 { get; set; }

            [ColumnName(@"col299")]
            public float Col299 { get; set; }

            [ColumnName(@"col300")]
            public float Col300 { get; set; }

            [ColumnName(@"col301")]
            public float Col301 { get; set; }

            [ColumnName(@"col302")]
            public float Col302 { get; set; }

            [ColumnName(@"col303")]
            public float Col303 { get; set; }

            [ColumnName(@"col304")]
            public float Col304 { get; set; }

            [ColumnName(@"col305")]
            public float Col305 { get; set; }

            [ColumnName(@"col306")]
            public float Col306 { get; set; }

            [ColumnName(@"col307")]
            public float Col307 { get; set; }

            [ColumnName(@"col308")]
            public float Col308 { get; set; }

            [ColumnName(@"col309")]
            public float Col309 { get; set; }

            [ColumnName(@"col310")]
            public float Col310 { get; set; }

            [ColumnName(@"col311")]
            public float Col311 { get; set; }

            [ColumnName(@"col312")]
            public float Col312 { get; set; }

            [ColumnName(@"col313")]
            public float Col313 { get; set; }

            [ColumnName(@"col314")]
            public float Col314 { get; set; }

            [ColumnName(@"col315")]
            public float Col315 { get; set; }

            [ColumnName(@"col316")]
            public float Col316 { get; set; }

            [ColumnName(@"col317")]
            public float Col317 { get; set; }

            [ColumnName(@"col318")]
            public float Col318 { get; set; }

            [ColumnName(@"col319")]
            public float Col319 { get; set; }

            [ColumnName(@"col320")]
            public float Col320 { get; set; }

            [ColumnName(@"col321")]
            public float Col321 { get; set; }

            [ColumnName(@"col322")]
            public float Col322 { get; set; }

            [ColumnName(@"col323")]
            public float Col323 { get; set; }

            [ColumnName(@"col324")]
            public float Col324 { get; set; }

            [ColumnName(@"col325")]
            public float Col325 { get; set; }

            [ColumnName(@"col326")]
            public float Col326 { get; set; }

            [ColumnName(@"col327")]
            public float Col327 { get; set; }

            [ColumnName(@"col328")]
            public float Col328 { get; set; }

            [ColumnName(@"col329")]
            public float Col329 { get; set; }

            [ColumnName(@"col330")]
            public float Col330 { get; set; }

            [ColumnName(@"col331")]
            public float Col331 { get; set; }

            [ColumnName(@"col332")]
            public float Col332 { get; set; }

            [ColumnName(@"col333")]
            public float Col333 { get; set; }

            [ColumnName(@"col334")]
            public float Col334 { get; set; }

            [ColumnName(@"col335")]
            public float Col335 { get; set; }

            [ColumnName(@"col336")]
            public float Col336 { get; set; }

            [ColumnName(@"col337")]
            public float Col337 { get; set; }

            [ColumnName(@"col338")]
            public float Col338 { get; set; }

            [ColumnName(@"col339")]
            public float Col339 { get; set; }

            [ColumnName(@"col340")]
            public float Col340 { get; set; }

            [ColumnName(@"col341")]
            public float Col341 { get; set; }

            [ColumnName(@"col342")]
            public float Col342 { get; set; }

            [ColumnName(@"col343")]
            public float Col343 { get; set; }

            [ColumnName(@"col344")]
            public float Col344 { get; set; }

            [ColumnName(@"col345")]
            public float Col345 { get; set; }

            [ColumnName(@"col346")]
            public float Col346 { get; set; }

            [ColumnName(@"col347")]
            public float Col347 { get; set; }

            [ColumnName(@"col348")]
            public float Col348 { get; set; }

            [ColumnName(@"col349")]
            public float Col349 { get; set; }

            [ColumnName(@"col350")]
            public float Col350 { get; set; }

            [ColumnName(@"col351")]
            public float Col351 { get; set; }

            [ColumnName(@"col352")]
            public float Col352 { get; set; }

            [ColumnName(@"col353")]
            public float Col353 { get; set; }

            [ColumnName(@"col354")]
            public float Col354 { get; set; }

            [ColumnName(@"col355")]
            public float Col355 { get; set; }

            [ColumnName(@"col356")]
            public float Col356 { get; set; }

            [ColumnName(@"col357")]
            public float Col357 { get; set; }

            [ColumnName(@"col358")]
            public float Col358 { get; set; }

            [ColumnName(@"col359")]
            public float Col359 { get; set; }

            [ColumnName(@"col360")]
            public float Col360 { get; set; }

            [ColumnName(@"col361")]
            public float Col361 { get; set; }

            [ColumnName(@"col362")]
            public float Col362 { get; set; }

            [ColumnName(@"col363")]
            public float Col363 { get; set; }

            [ColumnName(@"col364")]
            public float Col364 { get; set; }

            [ColumnName(@"col365")]
            public float Col365 { get; set; }

            [ColumnName(@"col366")]
            public float Col366 { get; set; }

            [ColumnName(@"col367")]
            public float Col367 { get; set; }

            [ColumnName(@"col368")]
            public float Col368 { get; set; }

            [ColumnName(@"col369")]
            public float Col369 { get; set; }

            [ColumnName(@"col370")]
            public float Col370 { get; set; }

            [ColumnName(@"col371")]
            public float Col371 { get; set; }

            [ColumnName(@"col372")]
            public float Col372 { get; set; }

            [ColumnName(@"col373")]
            public float Col373 { get; set; }

            [ColumnName(@"col374")]
            public float Col374 { get; set; }

            [ColumnName(@"col375")]
            public float Col375 { get; set; }

            [ColumnName(@"col376")]
            public float Col376 { get; set; }

            [ColumnName(@"col377")]
            public float Col377 { get; set; }

            [ColumnName(@"col378")]
            public float Col378 { get; set; }

            [ColumnName(@"col379")]
            public float Col379 { get; set; }

            [ColumnName(@"col380")]
            public float Col380 { get; set; }

            [ColumnName(@"col381")]
            public float Col381 { get; set; }

            [ColumnName(@"col382")]
            public float Col382 { get; set; }

            [ColumnName(@"col383")]
            public float Col383 { get; set; }

            [ColumnName(@"col384")]
            public float Col384 { get; set; }

            [ColumnName(@"col385")]
            public float Col385 { get; set; }

            [ColumnName(@"col386")]
            public float Col386 { get; set; }

            [ColumnName(@"col387")]
            public float Col387 { get; set; }

            [ColumnName(@"col388")]
            public float Col388 { get; set; }

            [ColumnName(@"col389")]
            public float Col389 { get; set; }

            [ColumnName(@"col390")]
            public float Col390 { get; set; }

            [ColumnName(@"col391")]
            public float Col391 { get; set; }

            [ColumnName(@"col392")]
            public float Col392 { get; set; }

            [ColumnName(@"col393")]
            public float Col393 { get; set; }

            [ColumnName(@"col394")]
            public float Col394 { get; set; }

            [ColumnName(@"col395")]
            public float Col395 { get; set; }

            [ColumnName(@"col396")]
            public float Col396 { get; set; }

            [ColumnName(@"col397")]
            public float Col397 { get; set; }

            [ColumnName(@"col398")]
            public float Col398 { get; set; }

            [ColumnName(@"col399")]
            public float Col399 { get; set; }

            [ColumnName(@"col400")]
            public float Col400 { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"col0")]
            public float Col0 { get; set; }

            [ColumnName(@"col1")]
            public float Col1 { get; set; }

            [ColumnName(@"col2")]
            public float Col2 { get; set; }

            [ColumnName(@"col3")]
            public float Col3 { get; set; }

            [ColumnName(@"col4")]
            public float Col4 { get; set; }

            [ColumnName(@"col5")]
            public float Col5 { get; set; }

            [ColumnName(@"col6")]
            public float Col6 { get; set; }

            [ColumnName(@"col7")]
            public float Col7 { get; set; }

            [ColumnName(@"col8")]
            public float Col8 { get; set; }

            [ColumnName(@"col9")]
            public float Col9 { get; set; }

            [ColumnName(@"col10")]
            public float Col10 { get; set; }

            [ColumnName(@"col11")]
            public float Col11 { get; set; }

            [ColumnName(@"col12")]
            public float Col12 { get; set; }

            [ColumnName(@"col13")]
            public float Col13 { get; set; }

            [ColumnName(@"col14")]
            public float Col14 { get; set; }

            [ColumnName(@"col15")]
            public float Col15 { get; set; }

            [ColumnName(@"col16")]
            public float Col16 { get; set; }

            [ColumnName(@"col17")]
            public float Col17 { get; set; }

            [ColumnName(@"col18")]
            public float Col18 { get; set; }

            [ColumnName(@"col19")]
            public float Col19 { get; set; }

            [ColumnName(@"col20")]
            public float Col20 { get; set; }

            [ColumnName(@"col21")]
            public float Col21 { get; set; }

            [ColumnName(@"col22")]
            public float Col22 { get; set; }

            [ColumnName(@"col23")]
            public float Col23 { get; set; }

            [ColumnName(@"col24")]
            public float Col24 { get; set; }

            [ColumnName(@"col25")]
            public float Col25 { get; set; }

            [ColumnName(@"col26")]
            public float Col26 { get; set; }

            [ColumnName(@"col27")]
            public float Col27 { get; set; }

            [ColumnName(@"col28")]
            public float Col28 { get; set; }

            [ColumnName(@"col29")]
            public float Col29 { get; set; }

            [ColumnName(@"col30")]
            public float Col30 { get; set; }

            [ColumnName(@"col31")]
            public float Col31 { get; set; }

            [ColumnName(@"col32")]
            public float Col32 { get; set; }

            [ColumnName(@"col33")]
            public float Col33 { get; set; }

            [ColumnName(@"col34")]
            public float Col34 { get; set; }

            [ColumnName(@"col35")]
            public float Col35 { get; set; }

            [ColumnName(@"col36")]
            public float Col36 { get; set; }

            [ColumnName(@"col37")]
            public float Col37 { get; set; }

            [ColumnName(@"col38")]
            public float Col38 { get; set; }

            [ColumnName(@"col39")]
            public float Col39 { get; set; }

            [ColumnName(@"col40")]
            public float Col40 { get; set; }

            [ColumnName(@"col41")]
            public float Col41 { get; set; }

            [ColumnName(@"col42")]
            public float Col42 { get; set; }

            [ColumnName(@"col43")]
            public float Col43 { get; set; }

            [ColumnName(@"col44")]
            public float Col44 { get; set; }

            [ColumnName(@"col45")]
            public float Col45 { get; set; }

            [ColumnName(@"col46")]
            public float Col46 { get; set; }

            [ColumnName(@"col47")]
            public float Col47 { get; set; }

            [ColumnName(@"col48")]
            public float Col48 { get; set; }

            [ColumnName(@"col49")]
            public float Col49 { get; set; }

            [ColumnName(@"col50")]
            public float Col50 { get; set; }

            [ColumnName(@"col51")]
            public float Col51 { get; set; }

            [ColumnName(@"col52")]
            public float Col52 { get; set; }

            [ColumnName(@"col53")]
            public float Col53 { get; set; }

            [ColumnName(@"col54")]
            public float Col54 { get; set; }

            [ColumnName(@"col55")]
            public float Col55 { get; set; }

            [ColumnName(@"col56")]
            public float Col56 { get; set; }

            [ColumnName(@"col57")]
            public float Col57 { get; set; }

            [ColumnName(@"col58")]
            public float Col58 { get; set; }

            [ColumnName(@"col59")]
            public float Col59 { get; set; }

            [ColumnName(@"col60")]
            public float Col60 { get; set; }

            [ColumnName(@"col61")]
            public float Col61 { get; set; }

            [ColumnName(@"col62")]
            public float Col62 { get; set; }

            [ColumnName(@"col63")]
            public float Col63 { get; set; }

            [ColumnName(@"col64")]
            public float Col64 { get; set; }

            [ColumnName(@"col65")]
            public float Col65 { get; set; }

            [ColumnName(@"col66")]
            public float Col66 { get; set; }

            [ColumnName(@"col67")]
            public float Col67 { get; set; }

            [ColumnName(@"col68")]
            public float Col68 { get; set; }

            [ColumnName(@"col69")]
            public float Col69 { get; set; }

            [ColumnName(@"col70")]
            public float Col70 { get; set; }

            [ColumnName(@"col71")]
            public float Col71 { get; set; }

            [ColumnName(@"col72")]
            public float Col72 { get; set; }

            [ColumnName(@"col73")]
            public float Col73 { get; set; }

            [ColumnName(@"col74")]
            public float Col74 { get; set; }

            [ColumnName(@"col75")]
            public float Col75 { get; set; }

            [ColumnName(@"col76")]
            public float Col76 { get; set; }

            [ColumnName(@"col77")]
            public float Col77 { get; set; }

            [ColumnName(@"col78")]
            public float Col78 { get; set; }

            [ColumnName(@"col79")]
            public float Col79 { get; set; }

            [ColumnName(@"col80")]
            public float Col80 { get; set; }

            [ColumnName(@"col81")]
            public float Col81 { get; set; }

            [ColumnName(@"col82")]
            public float Col82 { get; set; }

            [ColumnName(@"col83")]
            public float Col83 { get; set; }

            [ColumnName(@"col84")]
            public float Col84 { get; set; }

            [ColumnName(@"col85")]
            public float Col85 { get; set; }

            [ColumnName(@"col86")]
            public float Col86 { get; set; }

            [ColumnName(@"col87")]
            public float Col87 { get; set; }

            [ColumnName(@"col88")]
            public float Col88 { get; set; }

            [ColumnName(@"col89")]
            public float Col89 { get; set; }

            [ColumnName(@"col90")]
            public float Col90 { get; set; }

            [ColumnName(@"col91")]
            public float Col91 { get; set; }

            [ColumnName(@"col92")]
            public float Col92 { get; set; }

            [ColumnName(@"col93")]
            public float Col93 { get; set; }

            [ColumnName(@"col94")]
            public float Col94 { get; set; }

            [ColumnName(@"col95")]
            public float Col95 { get; set; }

            [ColumnName(@"col96")]
            public float Col96 { get; set; }

            [ColumnName(@"col97")]
            public float Col97 { get; set; }

            [ColumnName(@"col98")]
            public float Col98 { get; set; }

            [ColumnName(@"col99")]
            public float Col99 { get; set; }

            [ColumnName(@"col100")]
            public float Col100 { get; set; }

            [ColumnName(@"col101")]
            public float Col101 { get; set; }

            [ColumnName(@"col102")]
            public float Col102 { get; set; }

            [ColumnName(@"col103")]
            public float Col103 { get; set; }

            [ColumnName(@"col104")]
            public float Col104 { get; set; }

            [ColumnName(@"col105")]
            public float Col105 { get; set; }

            [ColumnName(@"col106")]
            public float Col106 { get; set; }

            [ColumnName(@"col107")]
            public float Col107 { get; set; }

            [ColumnName(@"col108")]
            public float Col108 { get; set; }

            [ColumnName(@"col109")]
            public float Col109 { get; set; }

            [ColumnName(@"col110")]
            public float Col110 { get; set; }

            [ColumnName(@"col111")]
            public float Col111 { get; set; }

            [ColumnName(@"col112")]
            public float Col112 { get; set; }

            [ColumnName(@"col113")]
            public float Col113 { get; set; }

            [ColumnName(@"col114")]
            public float Col114 { get; set; }

            [ColumnName(@"col115")]
            public float Col115 { get; set; }

            [ColumnName(@"col116")]
            public float Col116 { get; set; }

            [ColumnName(@"col117")]
            public float Col117 { get; set; }

            [ColumnName(@"col118")]
            public float Col118 { get; set; }

            [ColumnName(@"col119")]
            public float Col119 { get; set; }

            [ColumnName(@"col120")]
            public float Col120 { get; set; }

            [ColumnName(@"col121")]
            public float Col121 { get; set; }

            [ColumnName(@"col122")]
            public float Col122 { get; set; }

            [ColumnName(@"col123")]
            public float Col123 { get; set; }

            [ColumnName(@"col124")]
            public float Col124 { get; set; }

            [ColumnName(@"col125")]
            public float Col125 { get; set; }

            [ColumnName(@"col126")]
            public float Col126 { get; set; }

            [ColumnName(@"col127")]
            public float Col127 { get; set; }

            [ColumnName(@"col128")]
            public float Col128 { get; set; }

            [ColumnName(@"col129")]
            public float Col129 { get; set; }

            [ColumnName(@"col130")]
            public float Col130 { get; set; }

            [ColumnName(@"col131")]
            public float Col131 { get; set; }

            [ColumnName(@"col132")]
            public float Col132 { get; set; }

            [ColumnName(@"col133")]
            public float Col133 { get; set; }

            [ColumnName(@"col134")]
            public float Col134 { get; set; }

            [ColumnName(@"col135")]
            public float Col135 { get; set; }

            [ColumnName(@"col136")]
            public float Col136 { get; set; }

            [ColumnName(@"col137")]
            public float Col137 { get; set; }

            [ColumnName(@"col138")]
            public float Col138 { get; set; }

            [ColumnName(@"col139")]
            public float Col139 { get; set; }

            [ColumnName(@"col140")]
            public float Col140 { get; set; }

            [ColumnName(@"col141")]
            public float Col141 { get; set; }

            [ColumnName(@"col142")]
            public float Col142 { get; set; }

            [ColumnName(@"col143")]
            public float Col143 { get; set; }

            [ColumnName(@"col144")]
            public float Col144 { get; set; }

            [ColumnName(@"col145")]
            public float Col145 { get; set; }

            [ColumnName(@"col146")]
            public float Col146 { get; set; }

            [ColumnName(@"col147")]
            public float Col147 { get; set; }

            [ColumnName(@"col148")]
            public float Col148 { get; set; }

            [ColumnName(@"col149")]
            public float Col149 { get; set; }

            [ColumnName(@"col150")]
            public float Col150 { get; set; }

            [ColumnName(@"col151")]
            public float Col151 { get; set; }

            [ColumnName(@"col152")]
            public float Col152 { get; set; }

            [ColumnName(@"col153")]
            public float Col153 { get; set; }

            [ColumnName(@"col154")]
            public float Col154 { get; set; }

            [ColumnName(@"col155")]
            public float Col155 { get; set; }

            [ColumnName(@"col156")]
            public float Col156 { get; set; }

            [ColumnName(@"col157")]
            public float Col157 { get; set; }

            [ColumnName(@"col158")]
            public float Col158 { get; set; }

            [ColumnName(@"col159")]
            public float Col159 { get; set; }

            [ColumnName(@"col160")]
            public float Col160 { get; set; }

            [ColumnName(@"col161")]
            public float Col161 { get; set; }

            [ColumnName(@"col162")]
            public float Col162 { get; set; }

            [ColumnName(@"col163")]
            public float Col163 { get; set; }

            [ColumnName(@"col164")]
            public float Col164 { get; set; }

            [ColumnName(@"col165")]
            public float Col165 { get; set; }

            [ColumnName(@"col166")]
            public float Col166 { get; set; }

            [ColumnName(@"col167")]
            public float Col167 { get; set; }

            [ColumnName(@"col168")]
            public float Col168 { get; set; }

            [ColumnName(@"col169")]
            public float Col169 { get; set; }

            [ColumnName(@"col170")]
            public float Col170 { get; set; }

            [ColumnName(@"col171")]
            public float Col171 { get; set; }

            [ColumnName(@"col172")]
            public float Col172 { get; set; }

            [ColumnName(@"col173")]
            public float Col173 { get; set; }

            [ColumnName(@"col174")]
            public float Col174 { get; set; }

            [ColumnName(@"col175")]
            public float Col175 { get; set; }

            [ColumnName(@"col176")]
            public float Col176 { get; set; }

            [ColumnName(@"col177")]
            public float Col177 { get; set; }

            [ColumnName(@"col178")]
            public float Col178 { get; set; }

            [ColumnName(@"col179")]
            public float Col179 { get; set; }

            [ColumnName(@"col180")]
            public float Col180 { get; set; }

            [ColumnName(@"col181")]
            public float Col181 { get; set; }

            [ColumnName(@"col182")]
            public float Col182 { get; set; }

            [ColumnName(@"col183")]
            public float Col183 { get; set; }

            [ColumnName(@"col184")]
            public float Col184 { get; set; }

            [ColumnName(@"col185")]
            public float Col185 { get; set; }

            [ColumnName(@"col186")]
            public float Col186 { get; set; }

            [ColumnName(@"col187")]
            public float Col187 { get; set; }

            [ColumnName(@"col188")]
            public float Col188 { get; set; }

            [ColumnName(@"col189")]
            public float Col189 { get; set; }

            [ColumnName(@"col190")]
            public float Col190 { get; set; }

            [ColumnName(@"col191")]
            public float Col191 { get; set; }

            [ColumnName(@"col192")]
            public float Col192 { get; set; }

            [ColumnName(@"col193")]
            public float Col193 { get; set; }

            [ColumnName(@"col194")]
            public float Col194 { get; set; }

            [ColumnName(@"col195")]
            public float Col195 { get; set; }

            [ColumnName(@"col196")]
            public float Col196 { get; set; }

            [ColumnName(@"col197")]
            public float Col197 { get; set; }

            [ColumnName(@"col198")]
            public float Col198 { get; set; }

            [ColumnName(@"col199")]
            public float Col199 { get; set; }

            [ColumnName(@"col200")]
            public float Col200 { get; set; }

            [ColumnName(@"col201")]
            public float Col201 { get; set; }

            [ColumnName(@"col202")]
            public float Col202 { get; set; }

            [ColumnName(@"col203")]
            public float Col203 { get; set; }

            [ColumnName(@"col204")]
            public float Col204 { get; set; }

            [ColumnName(@"col205")]
            public float Col205 { get; set; }

            [ColumnName(@"col206")]
            public float Col206 { get; set; }

            [ColumnName(@"col207")]
            public float Col207 { get; set; }

            [ColumnName(@"col208")]
            public float Col208 { get; set; }

            [ColumnName(@"col209")]
            public float Col209 { get; set; }

            [ColumnName(@"col210")]
            public float Col210 { get; set; }

            [ColumnName(@"col211")]
            public float Col211 { get; set; }

            [ColumnName(@"col212")]
            public float Col212 { get; set; }

            [ColumnName(@"col213")]
            public float Col213 { get; set; }

            [ColumnName(@"col214")]
            public float Col214 { get; set; }

            [ColumnName(@"col215")]
            public float Col215 { get; set; }

            [ColumnName(@"col216")]
            public float Col216 { get; set; }

            [ColumnName(@"col217")]
            public float Col217 { get; set; }

            [ColumnName(@"col218")]
            public float Col218 { get; set; }

            [ColumnName(@"col219")]
            public float Col219 { get; set; }

            [ColumnName(@"col220")]
            public float Col220 { get; set; }

            [ColumnName(@"col221")]
            public float Col221 { get; set; }

            [ColumnName(@"col222")]
            public float Col222 { get; set; }

            [ColumnName(@"col223")]
            public float Col223 { get; set; }

            [ColumnName(@"col224")]
            public float Col224 { get; set; }

            [ColumnName(@"col225")]
            public float Col225 { get; set; }

            [ColumnName(@"col226")]
            public float Col226 { get; set; }

            [ColumnName(@"col227")]
            public float Col227 { get; set; }

            [ColumnName(@"col228")]
            public float Col228 { get; set; }

            [ColumnName(@"col229")]
            public float Col229 { get; set; }

            [ColumnName(@"col230")]
            public float Col230 { get; set; }

            [ColumnName(@"col231")]
            public float Col231 { get; set; }

            [ColumnName(@"col232")]
            public float Col232 { get; set; }

            [ColumnName(@"col233")]
            public float Col233 { get; set; }

            [ColumnName(@"col234")]
            public float Col234 { get; set; }

            [ColumnName(@"col235")]
            public float Col235 { get; set; }

            [ColumnName(@"col236")]
            public float Col236 { get; set; }

            [ColumnName(@"col237")]
            public float Col237 { get; set; }

            [ColumnName(@"col238")]
            public float Col238 { get; set; }

            [ColumnName(@"col239")]
            public float Col239 { get; set; }

            [ColumnName(@"col240")]
            public float Col240 { get; set; }

            [ColumnName(@"col241")]
            public float Col241 { get; set; }

            [ColumnName(@"col242")]
            public float Col242 { get; set; }

            [ColumnName(@"col243")]
            public float Col243 { get; set; }

            [ColumnName(@"col244")]
            public float Col244 { get; set; }

            [ColumnName(@"col245")]
            public float Col245 { get; set; }

            [ColumnName(@"col246")]
            public float Col246 { get; set; }

            [ColumnName(@"col247")]
            public float Col247 { get; set; }

            [ColumnName(@"col248")]
            public float Col248 { get; set; }

            [ColumnName(@"col249")]
            public float Col249 { get; set; }

            [ColumnName(@"col250")]
            public float Col250 { get; set; }

            [ColumnName(@"col251")]
            public float Col251 { get; set; }

            [ColumnName(@"col252")]
            public float Col252 { get; set; }

            [ColumnName(@"col253")]
            public float Col253 { get; set; }

            [ColumnName(@"col254")]
            public float Col254 { get; set; }

            [ColumnName(@"col255")]
            public float Col255 { get; set; }

            [ColumnName(@"col256")]
            public float Col256 { get; set; }

            [ColumnName(@"col257")]
            public float Col257 { get; set; }

            [ColumnName(@"col258")]
            public float Col258 { get; set; }

            [ColumnName(@"col259")]
            public float Col259 { get; set; }

            [ColumnName(@"col260")]
            public float Col260 { get; set; }

            [ColumnName(@"col261")]
            public float Col261 { get; set; }

            [ColumnName(@"col262")]
            public float Col262 { get; set; }

            [ColumnName(@"col263")]
            public float Col263 { get; set; }

            [ColumnName(@"col264")]
            public float Col264 { get; set; }

            [ColumnName(@"col265")]
            public float Col265 { get; set; }

            [ColumnName(@"col266")]
            public float Col266 { get; set; }

            [ColumnName(@"col267")]
            public float Col267 { get; set; }

            [ColumnName(@"col268")]
            public float Col268 { get; set; }

            [ColumnName(@"col269")]
            public float Col269 { get; set; }

            [ColumnName(@"col270")]
            public float Col270 { get; set; }

            [ColumnName(@"col271")]
            public float Col271 { get; set; }

            [ColumnName(@"col272")]
            public float Col272 { get; set; }

            [ColumnName(@"col273")]
            public float Col273 { get; set; }

            [ColumnName(@"col274")]
            public float Col274 { get; set; }

            [ColumnName(@"col275")]
            public float Col275 { get; set; }

            [ColumnName(@"col276")]
            public float Col276 { get; set; }

            [ColumnName(@"col277")]
            public float Col277 { get; set; }

            [ColumnName(@"col278")]
            public float Col278 { get; set; }

            [ColumnName(@"col279")]
            public float Col279 { get; set; }

            [ColumnName(@"col280")]
            public float Col280 { get; set; }

            [ColumnName(@"col281")]
            public float Col281 { get; set; }

            [ColumnName(@"col282")]
            public float Col282 { get; set; }

            [ColumnName(@"col283")]
            public float Col283 { get; set; }

            [ColumnName(@"col284")]
            public float Col284 { get; set; }

            [ColumnName(@"col285")]
            public float Col285 { get; set; }

            [ColumnName(@"col286")]
            public float Col286 { get; set; }

            [ColumnName(@"col287")]
            public float Col287 { get; set; }

            [ColumnName(@"col288")]
            public float Col288 { get; set; }

            [ColumnName(@"col289")]
            public float Col289 { get; set; }

            [ColumnName(@"col290")]
            public float Col290 { get; set; }

            [ColumnName(@"col291")]
            public float Col291 { get; set; }

            [ColumnName(@"col292")]
            public float Col292 { get; set; }

            [ColumnName(@"col293")]
            public float Col293 { get; set; }

            [ColumnName(@"col294")]
            public float Col294 { get; set; }

            [ColumnName(@"col295")]
            public float Col295 { get; set; }

            [ColumnName(@"col296")]
            public float Col296 { get; set; }

            [ColumnName(@"col297")]
            public float Col297 { get; set; }

            [ColumnName(@"col298")]
            public float Col298 { get; set; }

            [ColumnName(@"col299")]
            public float Col299 { get; set; }

            [ColumnName(@"col300")]
            public float Col300 { get; set; }

            [ColumnName(@"col301")]
            public float Col301 { get; set; }

            [ColumnName(@"col302")]
            public float Col302 { get; set; }

            [ColumnName(@"col303")]
            public float Col303 { get; set; }

            [ColumnName(@"col304")]
            public float Col304 { get; set; }

            [ColumnName(@"col305")]
            public float Col305 { get; set; }

            [ColumnName(@"col306")]
            public float Col306 { get; set; }

            [ColumnName(@"col307")]
            public float Col307 { get; set; }

            [ColumnName(@"col308")]
            public float Col308 { get; set; }

            [ColumnName(@"col309")]
            public float Col309 { get; set; }

            [ColumnName(@"col310")]
            public float Col310 { get; set; }

            [ColumnName(@"col311")]
            public float Col311 { get; set; }

            [ColumnName(@"col312")]
            public float Col312 { get; set; }

            [ColumnName(@"col313")]
            public float Col313 { get; set; }

            [ColumnName(@"col314")]
            public float Col314 { get; set; }

            [ColumnName(@"col315")]
            public float Col315 { get; set; }

            [ColumnName(@"col316")]
            public float Col316 { get; set; }

            [ColumnName(@"col317")]
            public float Col317 { get; set; }

            [ColumnName(@"col318")]
            public float Col318 { get; set; }

            [ColumnName(@"col319")]
            public float Col319 { get; set; }

            [ColumnName(@"col320")]
            public float Col320 { get; set; }

            [ColumnName(@"col321")]
            public float Col321 { get; set; }

            [ColumnName(@"col322")]
            public float Col322 { get; set; }

            [ColumnName(@"col323")]
            public float Col323 { get; set; }

            [ColumnName(@"col324")]
            public float Col324 { get; set; }

            [ColumnName(@"col325")]
            public float Col325 { get; set; }

            [ColumnName(@"col326")]
            public float Col326 { get; set; }

            [ColumnName(@"col327")]
            public float Col327 { get; set; }

            [ColumnName(@"col328")]
            public float Col328 { get; set; }

            [ColumnName(@"col329")]
            public float Col329 { get; set; }

            [ColumnName(@"col330")]
            public float Col330 { get; set; }

            [ColumnName(@"col331")]
            public float Col331 { get; set; }

            [ColumnName(@"col332")]
            public float Col332 { get; set; }

            [ColumnName(@"col333")]
            public float Col333 { get; set; }

            [ColumnName(@"col334")]
            public float Col334 { get; set; }

            [ColumnName(@"col335")]
            public float Col335 { get; set; }

            [ColumnName(@"col336")]
            public float Col336 { get; set; }

            [ColumnName(@"col337")]
            public float Col337 { get; set; }

            [ColumnName(@"col338")]
            public float Col338 { get; set; }

            [ColumnName(@"col339")]
            public float Col339 { get; set; }

            [ColumnName(@"col340")]
            public float Col340 { get; set; }

            [ColumnName(@"col341")]
            public float Col341 { get; set; }

            [ColumnName(@"col342")]
            public float Col342 { get; set; }

            [ColumnName(@"col343")]
            public float Col343 { get; set; }

            [ColumnName(@"col344")]
            public float Col344 { get; set; }

            [ColumnName(@"col345")]
            public float Col345 { get; set; }

            [ColumnName(@"col346")]
            public float Col346 { get; set; }

            [ColumnName(@"col347")]
            public float Col347 { get; set; }

            [ColumnName(@"col348")]
            public float Col348 { get; set; }

            [ColumnName(@"col349")]
            public float Col349 { get; set; }

            [ColumnName(@"col350")]
            public float Col350 { get; set; }

            [ColumnName(@"col351")]
            public float Col351 { get; set; }

            [ColumnName(@"col352")]
            public float Col352 { get; set; }

            [ColumnName(@"col353")]
            public float Col353 { get; set; }

            [ColumnName(@"col354")]
            public float Col354 { get; set; }

            [ColumnName(@"col355")]
            public float Col355 { get; set; }

            [ColumnName(@"col356")]
            public float Col356 { get; set; }

            [ColumnName(@"col357")]
            public float Col357 { get; set; }

            [ColumnName(@"col358")]
            public float Col358 { get; set; }

            [ColumnName(@"col359")]
            public float Col359 { get; set; }

            [ColumnName(@"col360")]
            public float Col360 { get; set; }

            [ColumnName(@"col361")]
            public float Col361 { get; set; }

            [ColumnName(@"col362")]
            public float Col362 { get; set; }

            [ColumnName(@"col363")]
            public float Col363 { get; set; }

            [ColumnName(@"col364")]
            public float Col364 { get; set; }

            [ColumnName(@"col365")]
            public float Col365 { get; set; }

            [ColumnName(@"col366")]
            public float Col366 { get; set; }

            [ColumnName(@"col367")]
            public float Col367 { get; set; }

            [ColumnName(@"col368")]
            public float Col368 { get; set; }

            [ColumnName(@"col369")]
            public float Col369 { get; set; }

            [ColumnName(@"col370")]
            public float Col370 { get; set; }

            [ColumnName(@"col371")]
            public float Col371 { get; set; }

            [ColumnName(@"col372")]
            public float Col372 { get; set; }

            [ColumnName(@"col373")]
            public float Col373 { get; set; }

            [ColumnName(@"col374")]
            public float Col374 { get; set; }

            [ColumnName(@"col375")]
            public float Col375 { get; set; }

            [ColumnName(@"col376")]
            public float Col376 { get; set; }

            [ColumnName(@"col377")]
            public float Col377 { get; set; }

            [ColumnName(@"col378")]
            public float Col378 { get; set; }

            [ColumnName(@"col379")]
            public float Col379 { get; set; }

            [ColumnName(@"col380")]
            public float Col380 { get; set; }

            [ColumnName(@"col381")]
            public float Col381 { get; set; }

            [ColumnName(@"col382")]
            public float Col382 { get; set; }

            [ColumnName(@"col383")]
            public float Col383 { get; set; }

            [ColumnName(@"col384")]
            public float Col384 { get; set; }

            [ColumnName(@"col385")]
            public float Col385 { get; set; }

            [ColumnName(@"col386")]
            public float Col386 { get; set; }

            [ColumnName(@"col387")]
            public float Col387 { get; set; }

            [ColumnName(@"col388")]
            public float Col388 { get; set; }

            [ColumnName(@"col389")]
            public float Col389 { get; set; }

            [ColumnName(@"col390")]
            public float Col390 { get; set; }

            [ColumnName(@"col391")]
            public float Col391 { get; set; }

            [ColumnName(@"col392")]
            public float Col392 { get; set; }

            [ColumnName(@"col393")]
            public float Col393 { get; set; }

            [ColumnName(@"col394")]
            public float Col394 { get; set; }

            [ColumnName(@"col395")]
            public float Col395 { get; set; }

            [ColumnName(@"col396")]
            public float Col396 { get; set; }

            [ColumnName(@"col397")]
            public float Col397 { get; set; }

            [ColumnName(@"col398")]
            public float Col398 { get; set; }

            [ColumnName(@"col399")]
            public float Col399 { get; set; }

            [ColumnName(@"col400")]
            public uint Col400 { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
